baseurl = "https://mjyi.github.io/Gemini/"
title = "Hugo Theme Gemini"
canonifyurls = true
paginate = 3
languageCode = "en-us"
MetaDataFormat = "yaml"
theme = "Gemini"
googleAnalytics = "" # delete or comment to disable Google Analytics JS generation
disqusShortname = "" #delete or comment to disable Disqus comments

[params]
  Keywords = ""
  Author = "Gemini"
  recentPostCount = 7
  intro = ["I am a iOS Developer", "Work in Hangzhou"]

[[params.social]]
  title = "Email"
  url = "mailto:itxuz@itxuz.com"
[[params.social]]
  title = "Github"
  url = "https://github.com/mjyi"
[[params.social]]
  title = "RSS"
  url = ""


[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -200
[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = -180
[[menu.main]]
  name = "About"
  url = "/about"
  weight = -160
